info:
  app:
    name: DevicesAPI
    version: 0.0.4
    description: My fabulous API of devices
server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: devicesapi
  profiles:
    active: dev
  security:
    user:
      name:  ${API_USER}
      password: ${API_PASSWORD}
      roles: ADMIN
    api-keys:
      clients:
        - key: ${DEVICE_API_KEY}
          secret-hash: ${DEVICE_API_SECRET_HASH}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:devices_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        # Batch configuration to optimize bulk inserts
        batch_size: 50
        order_inserts: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  jackson:
    serialization:
      fail-on-empty-beans: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      unwrap-root-value: false
logging:
  level:
    root: INFO                                      # Set the general logging level for the application
    org.hibernate.SQL: INFO                         # Log SQL statements executed by Hibernate
    org.hibernate.type.descriptor.sql: INFO        # Log SQL parameter binding
    org.springframework.data.jpa.repository: INFO  # Log JPA repository method calls
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0   # 100% for demo; lower in prod
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4317
#tracing:
#  url: http://localhost:4318/v1/traces
clear:
  all:
    cache:
      fixed:
        rate:



